<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class SportEventSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $sportEvents = [
            [
                'sport_id' => 1,
                'sport_division_id' => 1,
                'category' => 'Single Dance',
                'subcategory' => 'Modern standard',
                'name' => 'Waltz',
            ],
            [
                'sport_id' => 1,
                'sport_division_id' => 1,
                'category' => 'Single Dance',
                'subcategory' => 'Modern standard',
                'name' => 'tango',
            ],
            [
                'sport_id' => 1,
                'sport_division_id' => 1,
                'category' => 'Single Dance',
                'subcategory' => 'Modern standard',
                'name' => 'Viennese Waltz',
            ],
            [
                'sport_id' => 1,
                'sport_division_id' => 1,
                'category' => 'Single Dance',
                'subcategory' => 'Modern standard',
                'name' => 'Foxtrot',
            ],
            [
                'sport_id' => 1,
                'sport_division_id' => 1,
                'category' => 'Single Dance',
                'subcategory' => 'Modern standard',
                'name' => 'Quickstep',
            ],
            [
                'sport_id' => 1,
                'sport_division_id' => 1,
                'category' => 'Grade A',
                'subcategory' => 'Modern standard',
                'name' => 'W, T, VW, F, Q',
            ],
            [
                'sport_id' => 1,
                'sport_division_id' => 2,
                'category' => 'Single Dance',
                'subcategory' => 'Modern standard',
                'name' => 'Waltz',
            ],
            [
                'sport_id' => 1,
                'sport_division_id' => 2,
                'category' => 'Single Dance',
                'subcategory' => 'Modern standard',
                'name' => 'tango',
            ],
            [
                'sport_id' => 1,
                'sport_division_id' => 2,
                'category' => 'Single Dance',
                'subcategory' => 'Modern standard',
                'name' => 'Viennese Waltz',
            ],
            [
                'sport_id' => 1,
                'sport_division_id' => 2,
                'category' => 'Single Dance',
                'subcategory' => 'Modern standard',
                'name' => 'Foxtrot',
            ],
            [
                'sport_id' => 1,
                'sport_division_id' => 2,
                'category' => 'Single Dance',
                'subcategory' => 'Modern standard',
                'name' => 'Quickstep',
            ],
            [
                'sport_id' => 1,
                'sport_division_id' => 2,
                'category' => 'Grade A',
                'subcategory' => 'Modern standard',
                'name' => 'W, T, VW, F, Q',
            ],
            [
                'sport_id' => 1,
                'sport_division_id' => 1,
                'category' => 'Single Dance',
                'subcategory' => 'Latin American',
                'name' => 'Samba',
            ],
            [
                'sport_id' => 1,
                'sport_division_id' => 1,
                'category' => 'Single Dance',
                'subcategory' => 'Latin American',
                'name' => 'Cha-cha-cha',
            ],
            [
                'sport_id' => 1,
                'sport_division_id' => 1,
                'category' => 'Single Dance',
                'subcategory' => 'Latin American',
                'name' => 'Rumba',
            ],
            [
                'sport_id' => 1,
                'sport_division_id' => 1,
                'category' => 'Single Dance',
                'subcategory' => 'Latin American',
                'name' => 'Paso Doble',
            ],
            [
                'sport_id' => 1,
                'sport_division_id' => 1,
                'category' => 'Single Dance',
                'subcategory' => 'Latin American',
                'name' => 'Jive',
            ],
            [
                'sport_id' => 1,
                'sport_division_id' => 1,
                'category' => 'Grade A',
                'subcategory' => 'Latin American',
                'name' => 'S, C, R, PD, J',
            ],
            [
                'sport_id' => 1,
                'sport_division_id' => 2,
                'category' => 'Single Dance',
                'subcategory' => 'Latin American',
                'name' => 'Samba',
            ],
            [
                'sport_id' => 1,
                'sport_division_id' => 2,
                'category' => 'Single Dance',
                'subcategory' => 'Latin American',
                'name' => 'Cha-cha-cha',
            ],
            [
                'sport_id' => 1,
                'sport_division_id' => 2,
                'category' => 'Single Dance',
                'subcategory' => 'Latin American',
                'name' => 'Rumba',
            ],
            [
                'sport_id' => 1,
                'sport_division_id' => 2,
                'category' => 'Single Dance',
                'subcategory' => 'Latin American',
                'name' => 'Paso Doble',
            ],
            [
                'sport_id' => 1,
                'sport_division_id' => 2,
                'category' => 'Single Dance',
                'subcategory' => 'Latin American',
                'name' => 'Jive',
            ],
            [
                'sport_id' => 1,
                'sport_division_id' => 2,
                'category' => 'Grade A',
                'subcategory' => 'Latin American',
                'name' => 'S, C, R, PD, J',
            ],

            // Pencak Silat
            [
                'sport_id' => 2,
                'sport_division_id' => 2,
                'category' => 'Tanding',
                'subcategory' => 'Boys',
                'name' => 'Class A',
            ],
            [
                'sport_id' => 2,
                'sport_division_id' => 2,
                'category' => 'Tanding',
                'subcategory' => 'Boys',
                'name' => 'Class B',
            ],
            [
                'sport_id' => 2,
                'sport_division_id' => 2,
                'category' => 'Tanding',
                'subcategory' => 'Boys',
                'name' => 'Class C',
            ],
            [
                'sport_id' => 2,
                'sport_division_id' => 2,
                'category' => 'Tanding',
                'subcategory' => 'Boys',
                'name' => 'Class D',
            ],
            [
                'sport_id' => 2,
                'sport_division_id' => 2,
                'category' => 'Tanding',
                'subcategory' => 'Boys',
                'name' => 'Class E',
            ],
            [
                'sport_id' => 2,
                'sport_division_id' => 2,
                'category' => 'Tanding',
                'subcategory' => 'Girls',
                'name' => 'Class A',
            ],
            [
                'sport_id' => 2,
                'sport_division_id' => 2,
                'category' => 'Tanding',
                'subcategory' => 'Girls',
                'name' => 'Class B',
            ],
            [
                'sport_id' => 2,
                'sport_division_id' => 2,
                'category' => 'Tanding',
                'subcategory' => 'Girls',
                'name' => 'Class C',
            ],
            [
                'sport_id' => 2,
                'sport_division_id' => 2,
                'category' => 'Tanding',
                'subcategory' => 'Girls',
                'name' => 'Class D',
            ],
            [
                'sport_id' => 2,
                'sport_division_id' => 2,
                'category' => 'Tanding',
                'subcategory' => 'Girls',
                'name' => 'Class E',
            ],
            [
                'sport_id' => 2,
                'sport_division_id' => 2,
                'category' => 'Artistic',
                'subcategory' => null,
                'name' => 'Tungal',
            ],
            [
                'sport_id' => 2,
                'sport_division_id' => 2,
                'category' => 'Artistic',
                'subcategory' => null,
                'name' => 'Ganda',
            ],
            [
                'sport_id' => 2,
                'sport_division_id' => 2,
                'category' => 'Artistic',
                'subcategory' => null,
                'name' => 'Regu',
            ],

            // Archery
            [
                'sport_id' => 4,
                'sport_division_id' => 2,
                'category' => 'Boys',
                'subcategory' => null,
                'name' => '70-meter distance',
            ],
            [
                'sport_id' => 4,
                'sport_division_id' => 2,
                'category' => 'Boys',
                'subcategory' => null,
                'name' => '60-meter distance',
            ],
            [
                'sport_id' => 4,
                'sport_division_id' => 2,
                'category' => 'Boys',
                'subcategory' => null,
                'name' => '50-meter distance',
            ],
            [
                'sport_id' => 4,
                'sport_division_id' => 2,
                'category' => 'Boys',
                'subcategory' => null,
                'name' => '30-meter distance',
            ],
            [
                'sport_id' => 4,
                'sport_division_id' => 2,
                'category' => 'Boys',
                'subcategory' => null,
                'name' => '1440 round',
            ],
            [
                'sport_id' => 4,
                'sport_division_id' => 2,
                'category' => 'Boys',
                'subcategory' => null,
                'name' => 'Olympic Round (70 meters)',
            ],
            [
                'sport_id' => 4,
                'sport_division_id' => 2,
                'category' => 'Boys',
                'subcategory' => null,
                'name' => 'Team Event (70 meters)',
            ],
            [
                'sport_id' => 4,
                'sport_division_id' => 2,
                'category' => 'Boys',
                'subcategory' => null,
                'name' => 'Mixed Team (70 meters)',
            ],
            [
                'sport_id' => 4,
                'sport_division_id' => 2,
                'category' => 'Girls',
                'subcategory' => null,
                'name' => '70-meter distance',
            ],
            [
                'sport_id' => 4,
                'sport_division_id' => 2,
                'category' => 'Girls',
                'subcategory' => null,
                'name' => '60-meter distance',
            ],
            [
                'sport_id' => 4,
                'sport_division_id' => 2,
                'category' => 'Girls',
                'subcategory' => null,
                'name' => '50-meter distance',
            ],
            [
                'sport_id' => 4,
                'sport_division_id' => 2,
                'category' => 'Girls',
                'subcategory' => null,
                'name' => '30-meter distance',
            ],
            [
                'sport_id' => 4,
                'sport_division_id' => 2,
                'category' => 'Girls',
                'subcategory' => null,
                'name' => '1440 round',
            ],
            [
                'sport_id' => 4,
                'sport_division_id' => 2,
                'category' => 'Girls',
                'subcategory' => null,
                'name' => 'Olympic Round (70 meters)',
            ],
            [
                'sport_id' => 4,
                'sport_division_id' => 2,
                'category' => 'Girls',
                'subcategory' => null,
                'name' => 'Team Event (70 meters)',
            ],
            [
                'sport_id' => 4,
                'sport_division_id' => 2,
                'category' => 'Girls',
                'subcategory' => null,
                'name' => 'Mixed Team (70 meters)',
            ],

            // Arnis
            [
                'sport_id' => 5,
                'sport_division_id' => 2,
                'category' => 'Pinweight',
                'subcategory' => 'Boys',
                'name' => 'Full contact',
            ],
            [
                'sport_id' => 5,
                'sport_division_id' => 2,
                'category' => 'Pinweight',
                'subcategory' => 'Girls',
                'name' => 'Full contact',
            ],
            [
                'sport_id' => 5,
                'sport_division_id' => 2,
                'category' => 'Bantamweight',
                'subcategory' => 'Boys',
                'name' => 'Full contact',
            ],
            [
                'sport_id' => 5,
                'sport_division_id' => 2,
                'category' => 'Bantamweight',
                'subcategory' => 'Girls',
                'name' => 'Full contact',
            ],
            [
                'sport_id' => 5,
                'sport_division_id' => 2,
                'category' => 'Featherweight',
                'subcategory' => 'Boys',
                'name' => 'Full contact',
            ],
            [
                'sport_id' => 5,
                'sport_division_id' => 2,
                'category' => 'Featherweight',
                'subcategory' => 'Girls',
                'name' => 'Full contact',
            ],
            [
                'sport_id' => 5,
                'sport_division_id' => 2,
                'category' => 'Extra Lightweight',
                'subcategory' => 'Boys',
                'name' => 'Full contact',
            ],
            [
                'sport_id' => 5,
                'sport_division_id' => 2,
                'category' => 'Extra Lightweight',
                'subcategory' => 'Girls',
                'name' => 'Full contact',
            ],
            [
                'sport_id' => 5,
                'sport_division_id' => 2,
                'category' => 'Half Lightweight',
                'subcategory' => 'Boys',
                'name' => 'Full contact',
            ],
            [
                'sport_id' => 5,
                'sport_division_id' => 2,
                'category' => 'Half Lightweight',
                'subcategory' => 'Girls',
                'name' => 'Full contact',
            ],
            [
                'sport_id' => 5,
                'sport_division_id' => 1,
                'category' => 'Anyo Competition',
                'subcategory' => null,
                'name' => 'Individual Likha Anyo Single Weapon',
            ],
            [
                'sport_id' => 5,
                'sport_division_id' => 1,
                'category' => 'Anyo Competition',
                'subcategory' => null,
                'name' => 'Individual Likha Anyo Espada y Daga',
            ],
            [
                'sport_id' => 5,
                'sport_division_id' => 1,
                'category' => 'Anyo Competition',
                'subcategory' => null,
                'name' => 'Individual Likha Anyo Double Weapon',
            ],
            [
                'sport_id' => 5,
                'sport_division_id' => 1,
                'category' => 'Anyo Competition',
                'subcategory' => null,
                'name' => 'Team (Synchronized Mixed) Double Weapon',
            ],
            [
                'sport_id' => 5,
                'sport_division_id' => 1,
                'category' => 'Anyo Competition',
                'subcategory' => null,
                'name' => 'Team (Synchronized) Likha Anyo Single Weapon',
            ],
            [
                'sport_id' => 5,
                'sport_division_id' => 1,
                'category' => 'Anyo Competition',
                'subcategory' => null,
                'name' => 'Team (Synchronized) Likha Anyo Espada y Daga',
            ],
            [
                'sport_id' => 5,
                'sport_division_id' => 1,
                'category' => 'Anyo Competition',
                'subcategory' => null,
                'name' => 'Team (Synchronized) Likha Anyo Double Weapon',
            ],
            [
                'sport_id' => 5,
                'sport_division_id' => 2,
                'category' => 'Anyo Competition',
                'subcategory' => null,
                'name' => 'Individual Likha Anyo Single Weapon',
            ],
            [
                'sport_id' => 5,
                'sport_division_id' => 2,
                'category' => 'Anyo Competition',
                'subcategory' => null,
                'name' => 'Individual Likha Anyo Espada y Daga',
            ],
            [
                'sport_id' => 5,
                'sport_division_id' => 2,
                'category' => 'Anyo Competition',
                'subcategory' => null,
                'name' => 'Individual Likha Anyo Double Weapon',
            ],
            [
                'sport_id' => 5,
                'sport_division_id' => 2,
                'category' => 'Anyo Competition',
                'subcategory' => null,
                'name' => 'Team (Synchronized) Likha Anyo Single Weapon',
            ],
            [
                'sport_id' => 5,
                'sport_division_id' => 2,
                'category' => 'Anyo Competition',
                'subcategory' => null,
                'name' => 'Team (Synchronized) Likha Anyo Espada y Daga',
            ],
            [
                'sport_id' => 5,
                'sport_division_id' => 2,
                'category' => 'Anyo Competition',
                'subcategory' => null,
                'name' => 'Team (Synchronized) Likha Anyo Double Weapon',
            ],

            // Athletics
            [
                'sport_id' => 6,
                'sport_division_id' => 1,
                'category' => 'Track Events',
                'subcategory' => 'Boys',
                'name' => '100M',
            ],
            [
                'sport_id' => 6,
                'sport_division_id' => 1,
                'category' => 'Track Events',
                'subcategory' => 'Boys',
                'name' => '200M',
            ],
            [
                'sport_id' => 6,
                'sport_division_id' => 1,
                'category' => 'Track Events',
                'subcategory' => 'Boys',
                'name' => '400M',
            ],
            [
                'sport_id' => 6,
                'sport_division_id' => 1,
                'category' => 'Track Events',
                'subcategory' => 'Boys',
                'name' => '800M',
            ],
            [
                'sport_id' => 6,
                'sport_division_id' => 1,
                'category' => 'Track Events',
                'subcategory' => 'Boys',
                'name' => '1,500M',
            ],
            [
                'sport_id' => 6,
                'sport_division_id' => 1,
                'category' => 'Track Events',
                'subcategory' => 'Boys',
                'name' => '2,000M',
            ],
            [
                'sport_id' => 6,
                'sport_division_id' => 1,
                'category' => 'Track Events',
                'subcategory' => 'Boys',
                'name' => '3,000MSC',
            ],
            [
                'sport_id' => 6,
                'sport_division_id' => 1,
                'category' => 'Track Events',
                'subcategory' => 'Boys',
                'name' => '5,000M',
            ],
            [
                'sport_id' => 6,
                'sport_division_id' => 1,
                'category' => 'Track Events',
                'subcategory' => 'Boys',
                'name' => '100H',
            ],
            [
                'sport_id' => 6,
                'sport_division_id' => 1,
                'category' => 'Track Events',
                'subcategory' => 'Boys',
                'name' => '110H',
            ],
            [
                'sport_id' => 6,
                'sport_division_id' => 1,
                'category' => 'Track Events',
                'subcategory' => 'Boys',
                'name' => '400H',
            ],
            [
                'sport_id' => 6,
                'sport_division_id' => 1,
                'category' => 'Track Events',
                'subcategory' => 'Boys',
                'name' => '400H',
            ],
            [
                'sport_id' => 6,
                'sport_division_id' => 1,
                'category' => 'Track Events',
                'subcategory' => 'Boys',
                'name' => '4X400R',
            ],
            [
                'sport_id' => 6,
                'sport_division_id' => 1,
                'category' => 'Track Events',
                'subcategory' => 'Girls',
                'name' => '100M',
            ],
            [
                'sport_id' => 6,
                'sport_division_id' => 1,
                'category' => 'Track Events',
                'subcategory' => 'Girls',
                'name' => '200M',
            ],
            [
                'sport_id' => 6,
                'sport_division_id' => 1,
                'category' => 'Track Events',
                'subcategory' => 'Girls',
                'name' => '400M',
            ],
            [
                'sport_id' => 6,
                'sport_division_id' => 1,
                'category' => 'Track Events',
                'subcategory' => 'Girls',
                'name' => '800M',
            ],
            [
                'sport_id' => 6,
                'sport_division_id' => 1,
                'category' => 'Track Events',
                'subcategory' => 'Girls',
                'name' => '1,500M',
            ],
            [
                'sport_id' => 6,
                'sport_division_id' => 1,
                'category' => 'Track Events',
                'subcategory' => 'Girls',
                'name' => '2,000M',
            ],
            [
                'sport_id' => 6,
                'sport_division_id' => 1,
                'category' => 'Track Events',
                'subcategory' => 'Girls',
                'name' => '3,000MSC',
            ],
            [
                'sport_id' => 6,
                'sport_division_id' => 1,
                'category' => 'Track Events',
                'subcategory' => 'Girls',
                'name' => '5,000M',
            ],
            [
                'sport_id' => 6,
                'sport_division_id' => 1,
                'category' => 'Track Events',
                'subcategory' => 'Girls',
                'name' => '100H',
            ],
            [
                'sport_id' => 6,
                'sport_division_id' => 1,
                'category' => 'Track Events',
                'subcategory' => 'Girls',
                'name' => '110H',
            ],
            [
                'sport_id' => 6,
                'sport_division_id' => 1,
                'category' => 'Track Events',
                'subcategory' => 'Girls',
                'name' => '400H',
            ],
            [
                'sport_id' => 6,
                'sport_division_id' => 1,
                'category' => 'Track Events',
                'subcategory' => 'Girls',
                'name' => '400H',
            ],
            [
                'sport_id' => 6,
                'sport_division_id' => 1,
                'category' => 'Track Events',
                'subcategory' => 'Girls',
                'name' => '4X400R',
            ],
            [
                'sport_id' => 6,
                'sport_division_id' => 2,
                'category' => 'Track Events',
                'subcategory' => 'Boys',
                'name' => '100M',
            ],
            [
                'sport_id' => 6,
                'sport_division_id' => 2,
                'category' => 'Track Events',
                'subcategory' => 'Boys',
                'name' => '200M',
            ],
            [
                'sport_id' => 6,
                'sport_division_id' => 2,
                'category' => 'Track Events',
                'subcategory' => 'Boys',
                'name' => '400M',
            ],
            [
                'sport_id' => 6,
                'sport_division_id' => 2,
                'category' => 'Track Events',
                'subcategory' => 'Boys',
                'name' => '800M',
            ],
            [
                'sport_id' => 6,
                'sport_division_id' => 2,
                'category' => 'Track Events',
                'subcategory' => 'Boys',
                'name' => '1,500M',
            ],
            [
                'sport_id' => 6,
                'sport_division_id' => 2,
                'category' => 'Track Events',
                'subcategory' => 'Boys',
                'name' => '2,000M',
            ],
            [
                'sport_id' => 6,
                'sport_division_id' => 2,
                'category' => 'Track Events',
                'subcategory' => 'Boys',
                'name' => '3,000MSC',
            ],
            [
                'sport_id' => 6,
                'sport_division_id' => 2,
                'category' => 'Track Events',
                'subcategory' => 'Boys',
                'name' => '5,000M',
            ],
            [
                'sport_id' => 6,
                'sport_division_id' => 2,
                'category' => 'Track Events',
                'subcategory' => 'Boys',
                'name' => '100H',
            ],
            [
                'sport_id' => 6,
                'sport_division_id' => 2,
                'category' => 'Track Events',
                'subcategory' => 'Boys',
                'name' => '110H',
            ],
            [
                'sport_id' => 6,
                'sport_division_id' => 2,
                'category' => 'Track Events',
                'subcategory' => 'Boys',
                'name' => '400H',
            ],
            [
                'sport_id' => 6,
                'sport_division_id' => 2,
                'category' => 'Track Events',
                'subcategory' => 'Boys',
                'name' => '400H',
            ],
            [
                'sport_id' => 6,
                'sport_division_id' => 2,
                'category' => 'Track Events',
                'subcategory' => 'Boys',
                'name' => '4X400R',
            ],
            [
                'sport_id' => 6,
                'sport_division_id' => 2,
                'category' => 'Track Events',
                'subcategory' => 'Girls',
                'name' => '100M',
            ],
            [
                'sport_id' => 6,
                'sport_division_id' => 2,
                'category' => 'Track Events',
                'subcategory' => 'Girls',
                'name' => '200M',
            ],
            [
                'sport_id' => 6,
                'sport_division_id' => 2,
                'category' => 'Track Events',
                'subcategory' => 'Girls',
                'name' => '400M',
            ],
            [
                'sport_id' => 6,
                'sport_division_id' => 2,
                'category' => 'Track Events',
                'subcategory' => 'Girls',
                'name' => '800M',
            ],
            [
                'sport_id' => 6,
                'sport_division_id' => 2,
                'category' => 'Track Events',
                'subcategory' => 'Girls',
                'name' => '1,500M',
            ],
            [
                'sport_id' => 6,
                'sport_division_id' => 2,
                'category' => 'Track Events',
                'subcategory' => 'Girls',
                'name' => '2,000M',
            ],
            [
                'sport_id' => 6,
                'sport_division_id' => 2,
                'category' => 'Track Events',
                'subcategory' => 'Girls',
                'name' => '3,000MSC',
            ],
            [
                'sport_id' => 6,
                'sport_division_id' => 2,
                'category' => 'Track Events',
                'subcategory' => 'Girls',
                'name' => '5,000M',
            ],
            [
                'sport_id' => 6,
                'sport_division_id' => 2,
                'category' => 'Track Events',
                'subcategory' => 'Girls',
                'name' => '100H',
            ],
            [
                'sport_id' => 6,
                'sport_division_id' => 2,
                'category' => 'Track Events',
                'subcategory' => 'Girls',
                'name' => '110H',
            ],
            [
                'sport_id' => 6,
                'sport_division_id' => 2,
                'category' => 'Track Events',
                'subcategory' => 'Girls',
                'name' => '400H',
            ],
            [
                'sport_id' => 6,
                'sport_division_id' => 2,
                'category' => 'Track Events',
                'subcategory' => 'Girls',
                'name' => '400H',
            ],
            [
                'sport_id' => 6,
                'sport_division_id' => 2,
                'category' => 'Track Events',
                'subcategory' => 'Girls',
                'name' => '4X400R',
            ],
        ];

        DB::table('sport_events')->insert($sportEvents);
    }
}
