<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class SportEventSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $sportEvents = [
            [
                'sport_id' => 1,
                'sport_division_id' => 1,
                'category' => 'Single Dance',
                'name' => 'Modern standard (Waltz)',
            ],
            [
                'sport_id' => 1,
                'sport_division_id' => 1,
                'category' => 'Single Dance',
                'name' => 'Modern standard (tango)',
            ],
            [
                'sport_id' => 1,
                'sport_division_id' => 1,
                'category' => 'Single Dance',
                'name' => 'Modern standard (Viennese Waltz)',
            ],
            [
                'sport_id' => 1,
                'sport_division_id' => 1,
                'category' => 'Single Dance',
                'name' => 'Modern standard (Foxtrot)',
            ],
            [
                'sport_id' => 1,
                'sport_division_id' => 1,
                'category' => 'Single Dance',
                'name' => 'Modern standard (Quickstep)',
            ],
            [
                'sport_id' => 1,
                'sport_division_id' => 1,
                'category' => 'Grade A',
                'name' => 'Modern standard (W, T, VW, F, Q)',
            ],
            [
                'sport_id' => 1,
                'sport_division_id' => 2,
                'category' => 'Single Dance',
                'name' => 'Modern standard (Waltz)',
            ],
            [
                'sport_id' => 1,
                'sport_division_id' => 2,
                'category' => 'Single Dance',
                'name' => 'Modern standard (tango)',
            ],
            [
                'sport_id' => 1,
                'sport_division_id' => 2,
                'category' => 'Single Dance',
                'name' => 'Modern standard (Viennese Waltz)',
            ],
            [
                'sport_id' => 1,
                'sport_division_id' => 2,
                'category' => 'Single Dance',
                'name' => 'Modern standard (Foxtrot)',
            ],
            [
                'sport_id' => 1,
                'sport_division_id' => 2,
                'category' => 'Single Dance',
                'name' => 'Modern standard (Quickstep)',
            ],
            [
                'sport_id' => 1,
                'sport_division_id' => 2,
                'category' => 'Grade A',
                'name' => 'Modern standard (W, T, VW, F, Q)',
            ],
            [
                'sport_id' => 1,
                'sport_division_id' => 1,
                'category' => 'Single Dance',
                'name' => 'Latin American (Samba)',
            ],
            [
                'sport_id' => 1,
                'sport_division_id' => 1,
                'category' => 'Single Dance',
                'name' => 'Latin American (Cha-cha-cha)',
            ],
            [
                'sport_id' => 1,
                'sport_division_id' => 1,
                'category' => 'Single Dance',
                'name' => 'Latin American (Rumba)',
            ],
            [
                'sport_id' => 1,
                'sport_division_id' => 1,
                'category' => 'Single Dance',
                'name' => 'Latin American (Paso Doble)',
            ],
            [
                'sport_id' => 1,
                'sport_division_id' => 1,
                'category' => 'Single Dance',
                'name' => 'Latin American (Jive)',
            ],
            [
                'sport_id' => 1,
                'sport_division_id' => 1,
                'category' => 'Grade A',
                'name' => 'Latin American (S, C, R, PD, J)',
            ],
            [
                'sport_id' => 1,
                'sport_division_id' => 2,
                'category' => 'Single Dance',
                'name' => 'Latin American (Samba)',
            ],
            [
                'sport_id' => 1,
                'sport_division_id' => 2,
                'category' => 'Single Dance',
                'name' => 'Latin American (Cha-cha-cha)',
            ],
            [
                'sport_id' => 1,
                'sport_division_id' => 2,
                'category' => 'Single Dance',
                'name' => 'Latin American (Rumba)',
            ],
            [
                'sport_id' => 1,
                'sport_division_id' => 2,
                'category' => 'Single Dance',
                'name' => 'Latin American (Paso Doble)',
            ],
            [
                'sport_id' => 1,
                'sport_division_id' => 2,
                'category' => 'Single Dance',
                'name' => 'Latin American (Jive)',
            ],
            [
                'sport_id' => 1,
                'sport_division_id' => 2,
                'category' => 'Grade A',
                'name' => 'Latin American (S, C, R, PD, J)',
            ],

            // Pencak Silat
            [
                'sport_id' => 2,
                'sport_division_id' => 2,
                'category' => 'Tanding (Boys)',
                'name' => 'Class A',
            ],
            [
                'sport_id' => 2,
                'sport_division_id' => 2,
                'category' => 'Tanding (Boys)',
                'name' => 'Class B',
            ],
            [
                'sport_id' => 2,
                'sport_division_id' => 2,
                'category' => 'Tanding (Boys)',
                'name' => 'Class C',
            ],
            [
                'sport_id' => 2,
                'sport_division_id' => 2,
                'category' => 'Tanding (Boys)',
                'name' => 'Class D',
            ],
            [
                'sport_id' => 2,
                'sport_division_id' => 2,
                'category' => 'Tanding (Boys)',
                'name' => 'Class E',
            ],
            [
                'sport_id' => 2,
                'sport_division_id' => 2,
                'category' => 'Tanding (Girls)',
                'name' => 'Class A',
            ],
            [
                'sport_id' => 2,
                'sport_division_id' => 2,
                'category' => 'Tanding (Girls)',
                'name' => 'Class B',
            ],
            [
                'sport_id' => 2,
                'sport_division_id' => 2,
                'category' => 'Tanding (Girls)',
                'name' => 'Class C',
            ],
            [
                'sport_id' => 2,
                'sport_division_id' => 2,
                'category' => 'Tanding (Girls)',
                'name' => 'Class D',
            ],
            [
                'sport_id' => 2,
                'sport_division_id' => 2,
                'category' => 'Tanding (Girls)',
                'name' => 'Class E',
            ],
            [
                'sport_id' => 2,
                'sport_division_id' => 2,
                'category' => 'Artistic',
                'name' => 'Tungal',
            ],
            [
                'sport_id' => 2,
                'sport_division_id' => 2,
                'category' => 'Artistic',
                'name' => 'Ganda',
            ],
            [
                'sport_id' => 2,
                'sport_division_id' => 2,
                'category' => 'Artistic',
                'name' => 'Regu',
            ],

            // Archery
            [
                'sport_id' => 4,
                'sport_division_id' => 2,
                'category' => 'Boys',
                'name' => '70-meter distance',
            ],
            [
                'sport_id' => 4,
                'sport_division_id' => 2,
                'category' => 'Boys',
                'name' => '60-meter distance',
            ],
            [
                'sport_id' => 4,
                'sport_division_id' => 2,
                'category' => 'Boys',
                'name' => '50-meter distance',
            ],
            [
                'sport_id' => 4,
                'sport_division_id' => 2,
                'category' => 'Boys',
                'name' => '30-meter distance',
            ],
            [
                'sport_id' => 4,
                'sport_division_id' => 2,
                'category' => 'Boys',
                'name' => '1440 round',
            ],
            [
                'sport_id' => 4,
                'sport_division_id' => 2,
                'category' => 'Boys',
                'name' => 'Olympic Round (70 meters)',
            ],
            [
                'sport_id' => 4,
                'sport_division_id' => 2,
                'category' => 'Boys',
                'name' => 'Team Event (70 meters)',
            ],
            [
                'sport_id' => 4,
                'sport_division_id' => 2,
                'category' => 'Boys',
                'name' => 'Mixed Team (70 meters)',
            ],
            [
                'sport_id' => 4,
                'sport_division_id' => 2,
                'category' => 'Girls',
                'name' => '70-meter distance',
            ],
            [
                'sport_id' => 4,
                'sport_division_id' => 2,
                'category' => 'Girls',
                'name' => '60-meter distance',
            ],
            [
                'sport_id' => 4,
                'sport_division_id' => 2,
                'category' => 'Girls',
                'name' => '50-meter distance',
            ],
            [
                'sport_id' => 4,
                'sport_division_id' => 2,
                'category' => 'Girls',
                'name' => '30-meter distance',
            ],
            [
                'sport_id' => 4,
                'sport_division_id' => 2,
                'category' => 'Girls',
                'name' => '1440 round',
            ],
            [
                'sport_id' => 4,
                'sport_division_id' => 2,
                'category' => 'Girls',
                'name' => 'Olympic Round (70 meters)',
            ],
            [
                'sport_id' => 4,
                'sport_division_id' => 2,
                'category' => 'Girls',
                'name' => 'Team Event (70 meters)',
            ],
            [
                'sport_id' => 4,
                'sport_division_id' => 2,
                'category' => 'Girls',
                'name' => 'Mixed Team (70 meters)',
            ],

            // Arnis
            [
                'sport_id' => 5,
                'sport_division_id' => 2,
                'category' => 'Pinweight (Boys)',
                'name' => 'Full contact',
            ],
            [
                'sport_id' => 5,
                'sport_division_id' => 2,
                'category' => 'Pinweight (Girls)',
                'name' => 'Full contact',
            ],
            [
                'sport_id' => 5,
                'sport_division_id' => 2,
                'category' => 'Bantamweight (Boys)',
                'name' => 'Full contact',
            ],
            [
                'sport_id' => 5,
                'sport_division_id' => 2,
                'category' => 'Bantamweight (Girls)',
                'name' => 'Full contact',
            ],
            [
                'sport_id' => 5,
                'sport_division_id' => 2,
                'category' => 'Featherweight (Boys)',
                'name' => 'Full contact',
            ],
            [
                'sport_id' => 5,
                'sport_division_id' => 2,
                'category' => 'Featherweight (Girls)',
                'name' => 'Full contact',
            ],
            [
                'sport_id' => 5,
                'sport_division_id' => 2,
                'category' => 'Extra Lightweight (Boys)',
                'name' => 'Full contact',
            ],
            [
                'sport_id' => 5,
                'sport_division_id' => 2,
                'category' => 'Extra Lightweight (Girls)',
                'name' => 'Full contact',
            ],
            [
                'sport_id' => 5,
                'sport_division_id' => 2,
                'category' => 'Half Lightweight (Boys)',
                'name' => 'Full contact',
            ],
            [
                'sport_id' => 5,
                'sport_division_id' => 2,
                'category' => 'Half Lightweight (Girls)',
                'name' => 'Full contact',
            ],
            [
                'sport_id' => 5,
                'sport_division_id' => 1,
                'category' => 'Anyo Competition',
                'name' => 'Individual Likha Anyo Single Weapon',
            ],
            [
                'sport_id' => 5,
                'sport_division_id' => 1,
                'category' => 'Anyo Competition',
                'name' => 'Individual Likha Anyo Espada y Daga',
            ],
            [
                'sport_id' => 5,
                'sport_division_id' => 1,
                'category' => 'Anyo Competition',
                'name' => 'Individual Likha Anyo Double Weapon',
            ],
            [
                'sport_id' => 5,
                'sport_division_id' => 1,
                'category' => 'Anyo Competition',
                'name' => 'Team (Synchronized Mixed) Double Weapon',
            ],
            [
                'sport_id' => 5,
                'sport_division_id' => 1,
                'category' => 'Anyo Competition',
                'name' => 'Team (Synchronized) Likha Anyo Single Weapon',
            ],
            [
                'sport_id' => 5,
                'sport_division_id' => 1,
                'category' => 'Anyo Competition',
                'name' => 'Team (Synchronized) Likha Anyo Espada y Daga',
            ],
            [
                'sport_id' => 5,
                'sport_division_id' => 1,
                'category' => 'Anyo Competition',
                'name' => 'Team (Synchronized) Likha Anyo Double Weapon',
            ],
            [
                'sport_id' => 5,
                'sport_division_id' => 2,
                'category' => 'Anyo Competition',
                'name' => 'Individual Likha Anyo Single Weapon',
            ],
            [
                'sport_id' => 5,
                'sport_division_id' => 2,
                'category' => 'Anyo Competition',
                'name' => 'Individual Likha Anyo Espada y Daga',
            ],
            [
                'sport_id' => 5,
                'sport_division_id' => 2,
                'category' => 'Anyo Competition',
                'name' => 'Individual Likha Anyo Double Weapon',
            ],
            [
                'sport_id' => 5,
                'sport_division_id' => 2,
                'category' => 'Anyo Competition',
                'name' => 'Team (Synchronized) Likha Anyo Single Weapon',
            ],
            [
                'sport_id' => 5,
                'sport_division_id' => 2,
                'category' => 'Anyo Competition',
                'name' => 'Team (Synchronized) Likha Anyo Espada y Daga',
            ],
            [
                'sport_id' => 5,
                'sport_division_id' => 2,
                'category' => 'Anyo Competition',
                'name' => 'Team (Synchronized) Likha Anyo Double Weapon',
            ],

            // Athletics
            [
                'sport_id' => 6,
                'sport_division_id' => 1,
                'category' => 'Track Events (Boys)',
                'name' => '100M',
            ],
            [
                'sport_id' => 6,
                'sport_division_id' => 1,
                'category' => 'Track Events (Boys)',
                'name' => '200M',
            ],
            [
                'sport_id' => 6,
                'sport_division_id' => 1,
                'category' => 'Track Events (Boys)',
                'name' => '400M',
            ],
            [
                'sport_id' => 6,
                'sport_division_id' => 1,
                'category' => 'Track Events (Boys)',
                'name' => '800M',
            ],
            [
                'sport_id' => 6,
                'sport_division_id' => 1,
                'category' => 'Track Events (Boys)',
                'name' => '1,500M',
            ],
            [
                'sport_id' => 6,
                'sport_division_id' => 1,
                'category' => 'Track Events (Boys)',
                'name' => '2,000M',
            ],
            [
                'sport_id' => 6,
                'sport_division_id' => 1,
                'category' => 'Track Events (Boys)',
                'name' => '3,000MSC',
            ],
            [
                'sport_id' => 6,
                'sport_division_id' => 1,
                'category' => 'Track Events (Boys)',
                'name' => '5,000M',
            ],
            [
                'sport_id' => 6,
                'sport_division_id' => 1,
                'category' => 'Track Events (Boys)',
                'name' => '100H',
            ],
            [
                'sport_id' => 6,
                'sport_division_id' => 1,
                'category' => 'Track Events (Boys)',
                'name' => '110H',
            ],
            [
                'sport_id' => 6,
                'sport_division_id' => 1,
                'category' => 'Track Events (Boys)',
                'name' => '400H',
            ],
            [
                'sport_id' => 6,
                'sport_division_id' => 1,
                'category' => 'Track Events (Boys)',
                'name' => '400H',
            ],
            [
                'sport_id' => 6,
                'sport_division_id' => 1,
                'category' => 'Track Events (Boys)',
                'name' => '4X400R',
            ],
            [
                'sport_id' => 6,
                'sport_division_id' => 1,
                'category' => 'Track Events (Girls)',
                'name' => '100M',
            ],
            [
                'sport_id' => 6,
                'sport_division_id' => 1,
                'category' => 'Track Events (Girls)',
                'name' => '200M',
            ],
            [
                'sport_id' => 6,
                'sport_division_id' => 1,
                'category' => 'Track Events (Girls)',
                'name' => '400M',
            ],
            [
                'sport_id' => 6,
                'sport_division_id' => 1,
                'category' => 'Track Events (Girls)',
                'name' => '800M',
            ],
            [
                'sport_id' => 6,
                'sport_division_id' => 1,
                'category' => 'Track Events (Girls)',
                'name' => '1,500M',
            ],
            [
                'sport_id' => 6,
                'sport_division_id' => 1,
                'category' => 'Track Events (Girls)',
                'name' => '2,000M',
            ],
            [
                'sport_id' => 6,
                'sport_division_id' => 1,
                'category' => 'Track Events (Girls)',
                'name' => '3,000MSC',
            ],
            [
                'sport_id' => 6,
                'sport_division_id' => 1,
                'category' => 'Track Events (Girls)',
                'name' => '5,000M',
            ],
            [
                'sport_id' => 6,
                'sport_division_id' => 1,
                'category' => 'Track Events (Girls)',
                'name' => '100H',
            ],
            [
                'sport_id' => 6,
                'sport_division_id' => 1,
                'category' => 'Track Events (Girls)',
                'name' => '110H',
            ],
            [
                'sport_id' => 6,
                'sport_division_id' => 1,
                'category' => 'Track Events (Girls)',
                'name' => '400H',
            ],
            [
                'sport_id' => 6,
                'sport_division_id' => 1,
                'category' => 'Track Events (Girls)',
                'name' => '400H',
            ],
            [
                'sport_id' => 6,
                'sport_division_id' => 1,
                'category' => 'Track Events (Girls)',
                'name' => '4X400R',
            ],
            [
                'sport_id' => 6,
                'sport_division_id' => 2,
                'category' => 'Track Events (Boys)',
                'name' => '100M',
            ],
            [
                'sport_id' => 6,
                'sport_division_id' => 2,
                'category' => 'Track Events (Boys)',
                'name' => '200M',
            ],
            [
                'sport_id' => 6,
                'sport_division_id' => 2,
                'category' => 'Track Events (Boys)',
                'name' => '400M',
            ],
            [
                'sport_id' => 6,
                'sport_division_id' => 2,
                'category' => 'Track Events (Boys)',
                'name' => '800M',
            ],
            [
                'sport_id' => 6,
                'sport_division_id' => 2,
                'category' => 'Track Events (Boys)',
                'name' => '1,500M',
            ],
            [
                'sport_id' => 6,
                'sport_division_id' => 2,
                'category' => 'Track Events (Boys)',
                'name' => '2,000M',
            ],
            [
                'sport_id' => 6,
                'sport_division_id' => 2,
                'category' => 'Track Events (Boys)',
                'name' => '3,000MSC',
            ],
            [
                'sport_id' => 6,
                'sport_division_id' => 2,
                'category' => 'Track Events (Boys)',
                'name' => '5,000M',
            ],
            [
                'sport_id' => 6,
                'sport_division_id' => 2,
                'category' => 'Track Events (Boys)',
                'name' => '100H',
            ],
            [
                'sport_id' => 6,
                'sport_division_id' => 2,
                'category' => 'Track Events (Boys)',
                'name' => '110H',
            ],
            [
                'sport_id' => 6,
                'sport_division_id' => 2,
                'category' => 'Track Events (Boys)',
                'name' => '400H',
            ],
            [
                'sport_id' => 6,
                'sport_division_id' => 2,
                'category' => 'Track Events (Boys)',
                'name' => '400H',
            ],
            [
                'sport_id' => 6,
                'sport_division_id' => 2,
                'category' => 'Track Events (Boys)',
                'name' => '4X400R',
            ],
            [
                'sport_id' => 6,
                'sport_division_id' => 2,
                'category' => 'Track Events (Girls)',
                'name' => '100M',
            ],
            [
                'sport_id' => 6,
                'sport_division_id' => 2,
                'category' => 'Track Events (Girls)',
                'name' => '200M',
            ],
            [
                'sport_id' => 6,
                'sport_division_id' => 2,
                'category' => 'Track Events (Girls)',
                'name' => '400M',
            ],
            [
                'sport_id' => 6,
                'sport_division_id' => 2,
                'category' => 'Track Events (Girls)',
                'name' => '800M',
            ],
            [
                'sport_id' => 6,
                'sport_division_id' => 2,
                'category' => 'Track Events (Girls)',
                'name' => '1,500M',
            ],
            [
                'sport_id' => 6,
                'sport_division_id' => 2,
                'category' => 'Track Events (Girls)',
                'name' => '2,000M',
            ],
            [
                'sport_id' => 6,
                'sport_division_id' => 2,
                'category' => 'Track Events (Girls)',
                'name' => '3,000MSC',
            ],
            [
                'sport_id' => 6,
                'sport_division_id' => 2,
                'category' => 'Track Events (Girls)',
                'name' => '5,000M',
            ],
            [
                'sport_id' => 6,
                'sport_division_id' => 2,
                'category' => 'Track Events (Girls)',
                'name' => '100H',
            ],
            [
                'sport_id' => 6,
                'sport_division_id' => 2,
                'category' => 'Track Events (Girls)',
                'name' => '110H',
            ],
            [
                'sport_id' => 6,
                'sport_division_id' => 2,
                'category' => 'Track Events (Girls)',
                'name' => '400H',
            ],
            [
                'sport_id' => 6,
                'sport_division_id' => 2,
                'category' => 'Track Events (Girls)',
                'name' => '400H',
            ],
            [
                'sport_id' => 6,
                'sport_division_id' => 2,
                'category' => 'Track Events (Girls)',
                'name' => '4X400R',
            ],
        ];

        DB::table('sport_events')->insert($sportEvents);
    }
}
